[package]
name = "rust-decompress"
version = "0.1.0"
edition = "2021"
author = "Christian Brewer"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
